In [7]:
import mxnet as mx
from mxnet import autograd

mx.test_utils.set_default_context(mx.context.gpu())

a = mx.nd.zeros((100, 50))
b = mx.nd.zeros((100, 50))

c = a * b
c *= 1
print(c)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 100x50 @gpu(0)>


In [8]:
a = mx.nd.zeros((100, 50), ctx=mx.context.cpu())
b = mx.nd.zeros((100, 50))

c = a * b
c *= 1
print(c)

MXNetError: [20:34:15] src/imperative/./imperative_utils.h:70: Check failed: inputs[i]->ctx().dev_mask() == ctx.dev_mask() (2 vs. 1) Operator broadcast_mul require all inputs live on the same context. But the first argument is on cpu(0) while the 2-th argument is on gpu(0)

Stack trace returned 10 entries:
[bt] (0) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x39022a) [0x7fc50f1b622a]
[bt] (1) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x390861) [0x7fc50f1b6861]
[bt] (2) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2b8d7ed) [0x7fc5119b37ed]
[bt] (3) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2b94589) [0x7fc5119ba589]
[bt] (4) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2aac1e9) [0x7fc5118d21e9]
[bt] (5) /home/shared/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x6f) [0x7fc5118d27df]
[bt] (6) /home/shared/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fc5621e9ec0]
[bt] (7) /home/shared/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fc5621e987d]
[bt] (8) /home/shared/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc5623ffe4e]
[bt] (9) /home/shared/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13885) [0x7fc562400885]



In [29]:
with autograd.record():
    
    x = mx.random.randn(2, 2)
    x.attach_grad()

    y = x ** 2
    y.attach_grad()
    
    z = y.mean()
    print(f"{x} - {y}")

print(f"{type(x)} - {type(y)}")

print(f"{x.grad} - {y.grad}")

z.backward()

print(f"{x.grad} - {y.grad}")
print(f"{x / 2}")


[[-1.1774861  -0.8099558 ]
 [-0.19443172 -1.8001759 ]]
<NDArray 2x2 @gpu(0)> - 
[[1.3864734  0.65602833]
 [0.03780369 3.2406335 ]]
<NDArray 2x2 @gpu(0)>
<class 'mxnet.ndarray.ndarray.NDArray'> - <class 'mxnet.ndarray.ndarray.NDArray'>

[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @gpu(0)> - 
[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @gpu(0)>

[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @gpu(0)> - 
[[0.25 0.25]
 [0.25 0.25]]
<NDArray 2x2 @gpu(0)>

[[-0.58874303 -0.4049779 ]
 [-0.09721586 -0.90008795]]
<NDArray 2x2 @gpu(0)>
